### ISSUE TITLE
Client meeting minutes

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#12]
Task title ID: #12

This task is about recording the minutes of the first meeting with the client based on the responses we received based on the questions asked. 

The goals of the recording the minutes is to clarify the requirements

The success criteria is to be able to collate all responses to the questions that we have for the client in a clear manner. 

The allocated time of the meeting was at 9.50am. 

The start date of the task was 7 September 2023 and the end date was 8 September 2023.

The task owner is Carmen. 

The status of the task is currently completed. 

The priority of the task is high.

**Comment by 2201680** [comment]
The work done was to collate all responses from our client based on the questions that we have discussed and finalised according to the requirements stated in the project description document, for the 1st meeting . During the meeting the responses was recorded in a word document and was then reorganized into a table format before sending it back to our client to vet through it. 

This work has been committed to the repo. 

The work allows us to have a clearer idea and understanding of the different requirements which are required for the functional and non functional requirements. 

The start date of the work done was 7 September 2023 and the end date was 8 September 2023.
