### ISSUE TITLE
Assumptions and Dependencies

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#27]
Task title ID: #27

The task and goals is to list down all the assumptions that we have to make the project doable. Dependencies are for components that for without them, the system would not work.

The goals is to determine the assumptions and dependencies for our requirements.

The success criteria is to list down the appropriate assumptions.

The start date of the task was 18 September 2023 and the end date was 20 September 2023.

The task owner is Kenan.

The status of the task is currently completed.

The priority of the task is high.

**Comment by kenantan32** [comment]
The work done was to list down all the assumptions that we have to make the project doable. Dependencies are for components that for without them, the system would not work.

The work allows us to have appropriate assumptions and dependencies for our project

The start date of the work done was 18 September 2023 and the end date was 20 September 2023.
