### ISSUE TITLE
Activity Diagram

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#28]

**Comment by JcCassano** [comment]
Task title ID: #28

This task is about documenting the completion of the Activity Diagram, which represents the workflow and interactions within the M1 report writing system. The Activity Diagram serves as a visual representation of the system's functionality.

The goals of this task are to confirm that the Activity Diagram accurately reflects the system's workflow as outlined in the project description and discussed during previous client meetings.

The completion criteria for this task require validating the accuracy and alignment of the Activity Diagram with project requirements and system behavior, ensuring consistency with functional requirements, and conducting a stakeholder review meeting to address discrepancies or revisions, ensuring an accurate representation of the system's workflow for effective communication.

The allocated time is 3 days.

The start date of the task was on 18 September 2023 and the end date is 20 September 2023 .

The owner of the task is Joseph.

The status of the task is currently "Completed".

The priority requirement is high.
