### ISSUE TITLE
Object Oriented Analysis

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#31]
Task title ID: #31

This task is to conduct the appropriate object oriented analysis for the class diagram.

The goal was to come up with the class diagram.

The completion criteria is to ensure that the objected oriented analysis conducted is accurate and according to the client's requirements.

The allocated time was 2 days.

The start date of the task is 26 October 2023 and the end date is 27 October 2023.

The owners of the task is Kenan.

The status of the task is completed.

The priority requirement was high.

**Comment by kenantan32** [comment]
The work done was with reference to the object-oriented analysis of the class diagram. We have to analyze the classes and their relationships within the diagram.

The work has been committed to the repository, capturing the object-oriented analysis findings.

The successful development involved in performing an in-depth object-oriented analysis to refine the class diagram.

The task's success criteria involved ensuring that the object-oriented analysis accurately identified the classes, their attributes, methods, and relationships.

The work on the object-oriented analysis, including the refinement of the class diagram, began on 26 October 2023 and ended on 27 October 2023.
