### ISSUE TITLE
Identifying Classes and Objects

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#32]
Task title ID: #32

This task is to identifying the appropriate classes and objects for the class diagram.

The goal was to come up with the class diagram.

The completion criteria is to ensure that the class and objects identified is accurate and according to the client's requirements.

The allocated time was 2 days.

The start date of the task is 26 October 2023 and the end date is 27 October 2023.

The owners of the task is Kenan.

The status of the task is completed.

The priority requirement was high.

**Comment by kenantan32** [comment]
The work done was with reference to object-oriented analysis for identifying the appropriate classes and objects for the class diagram. We have to analyze and identify the classes and objects that best represent the system.

The work has been committed to the repository, documenting the results of the object-oriented analysis.

The successful development involved performing object-oriented analysis to determine the most suitable classes and objects.

The task's success criteria involved ensuring that the object-oriented analysis accurately identified the necessary classes and objects, meeting the client's requirements.

The work on object-oriented analysis for class and object identification began on 26 October 2023 and ended on 27 October 2023.
