### ISSUE TITLE
Noun Extraction

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#35]
Task title ID: #35

This task is to extract the appropriate nouns for the class diagram.

The goal was to come up with the class diagram.

The completion criteria is to ensure that the extracted nouns is accurate and according to the client's requirements.

The allocated time was 2 days.

The start date of the task is 26 October 2023 and the end date is 27 October 2023.

The owners of the task is Kenan.

The status of the task is completed.

The priority requirement was high.

**Comment by kenantan32** [comment]
The work done was related to the extraction of appropriate nouns for the class diagram. The objective was to identify and select nouns that accurately represent the system's components.

The extracted nouns have been documented and stored in the repository.

The successful completion of this task involved a detailed analysis of the system's requirements and extracting nouns that align with the class diagram's design.

The task's success criteria were met by ensuring that the extracted nouns accurately reflected the system's architecture and satisfied the client's requirements.

The work on extracting appropriate nouns for the class diagram commenced on 26 October 2023 and was successfully completed on 27 October 2023.
