### ISSUE TITLE
Noun Identification

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#36]
Task title ID: #36

This task is to identify the appropriate nouns for the class diagram.

The goal was to come up with the class diagram.

The completion criteria is to ensure that the nouns identified is accurate and according to the client's requirements.

The allocated time was 2 days.

The start date of the task is 26 October 2023 and the end date is 27 October 2023.

The owners of the task is Kenan.

The status of the task is completed.

The priority requirement was high.

**Comment by kenantan32** [comment]
The work done was with reference to identifying nouns for the class diagram. We have to carefully select nouns that accurately represent the system's components.

The results of the noun identification have been documented and committed to the repository.

The successful development involved analyzing the system's requirements and performing noun identification to select the most appropriate nouns for the class diagram.

The task's success criteria involved ensuring that the nouns identified accurately reflected the system and met the client's requirements.

The work on noun identification for the class diagram began on 26 October 2023 and ended on 27 October 2023.
