### ISSUE TITLE
Removing Duplicates and Converting to Singular

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#37]
Task title ID: #37

This task is to remove the duplicates and convert them to singular for the class diagram.

The goal was to come up with the class diagram.

The completion criteria is to ensure that the correct duplicates are removed and converted to singular and according to the client's requirements.

The allocated time was 2 days.

The start date of the task is 26 October 2023 and the end date is 27 October 2023.

The owners of the task is Kenan.

The status of the task is completed.

The priority requirement was high.

**Comment by kenantan32** [comment]
The work done was with reference to removing duplicates and converting them to singular for the class diagram. We had to ensure that the correct duplicates were removed and that singular forms were used, aligning with the client's requirements.

The results of the removal of duplicates and conversion to singular have been documented and committed to the repository.

The successful development involved carefully reviewing the class diagram to identify and eliminate duplicates while ensuring singular naming conventions were followed.

The task's success criteria involved verifying that the duplicates were correctly removed and that singular forms were applied as per the client's requirements.

The work on removing duplicates and converting to singular for the class diagram began on 26 October 2023 and ended on 27 October 2023.
