### ISSUE TITLE
Identify Candidate Classes

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#38]
Task title ID: #38

This task is to identify the candidate classes for the class diagram.

The goal was to come up with the class diagram.

The completion criteria is to ensure that the identified candidate classes is accurate and according to the client's requirements.

The allocated time was 2 days.

The start date of the task is 26 October 2023 and the end date is 27 October 2023.

The owners of the task is Kenan.

The status of the task is completed.

The priority requirement was high.

**Comment by kenantan32** [comment]
The work done was with reference to identifying candidate classes for the class diagram. We had to carefully analyze and select potential classes that accurately represent the system's components.

The results of the candidate class identification have been documented and committed to the repository.

The successful development involved conducting a thorough analysis of the system's requirements and identifying candidate classes that align with the class diagram's design.

The task's success criteria involved ensuring that the identified candidate classes accurately reflected the system's architecture and met the client's requirements.

The work on identifying candidate classes for the class diagram began on 26 October 2023 and ended on 27 October 2023.
