### ISSUE TITLE
Milestone 1 powerpoint slides

### ISSUE THREAD

**Issue by kenantan32** [denmire/INF2001-TeamprojectP9Grp6#5]
Task title ID: #5

This task is where we developed a set of informative PowerPoint slides elucidating the various roles within the system and delineating their interactions, providing developers with a visual and comprehensive understanding of the complex system dynamics.

The goal was to achieve clarity in every role's engagement with the system. 

The completion criteria for this task involve ensuring that the PowerPoint slides are accurately crafted and align with the team's understanding, verifying their coherence with project objectives and system interactions.

The allocated time is 5 days.

The start date of the task was on 16 September 2023 and the end date is 20 September 2023 .

The owners of the task are Joseph and Carmen.

The status of the task is currently "Completed".

The priority requirement is Medium.

**Comment by JcCassano** [comment]
The work was done with reference to the minutes and the requirements as stated in the project description. During the process, I have to firstly sort out the requirements between functional and other requirements before listing it down.

The work has been committed to the reposition.

The successful development of the M1 PowerPoint slides aims to enhance the overall project comprehension..

The task's success criteria involve ensuring that each facet of the project, as illustrated in the slides, is distinctly articulated and readily understandable for effective client communication.

The work on the Product Functionality began on September 16, 2023, and concluded on September 20, 2023.
