### ISSUE TITLE
Documentation of Code

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#57]
Task title ID: #57

This task is about documenting the sets of wireframe to allow the users to understand the flow of the prototype.

The goals of the documentation is to match the use cases as stated in M1 and M2. 

The success criteria is to ensure that the all the wireframe sets are documented and matches with the use cases and the requirements. 

The start date of the task is on 29 October 2023 and the end date is 5 November 2023.

The owner of this task is Carmen.

The status of the task is completed 

The priority of the task was high.

**Comment by 2201680** [comment]
The work one consist of firstly ensuring that the sets prototype matches to what was mentioned in the use case description as well as what was stated in the requirements.

The work has been committed to the repo. 

The documentation affects how the client will understand the deliverable.

The success criteria is to ensure that the  prototype matches with all the use cases description and requirements.

The start date is 29 October 2023 and the end date is 5 November 2023.
