### ISSUE TITLE
Milestone 1 report

### ISSUE THREAD

**Issue by kenantan32** [denmire/INF2001-TeamprojectP9Grp6#6]
Task title ID: #06
To compile all information gathered and write a report for milestone 1.
Goal is to write a report for the planning phase of the report.
Considered success when report has been submitted.
Allocated time is 2 weeks.
Start 11 Sep, End 23 Sep.
Owner of task belongs to the whole team as it is a team responsibility.
Status is "Completed".
Priority was "High".

**Comment by denmire** [comment]
Report has been written with the cooperation of every team member.
Work has been committed to the repo.
Considered completed as we have submitted the report on time.
Start 11 Sep, End 23 Sep.
