### ISSUE TITLE
What went well in M1?

### ISSUE THREAD

**Issue by denmire** [denmire/INF2001-TeamprojectP9Grp6#69]

**Comment by denmire** [comment]
Task distribution was very smooth. Everyone managed to complete their task on time.

**Comment by 2201680** [comment]
I think even though we are a 4 man team but we handle it pretty well in completing the deliverables on time and managing our time.

**Comment by kenantan32** [comment]
Our time management went well. We managed to complete each section, with our use case diagram and descriptions being completed earlier than the other smaller sections.

**Comment by kenantan32** [comment]
Communication was effective with Ivan leading and assigning to the other team members.

**Comment by kenantan32** [comment]
Effort was there from every team member.
