### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by kenantan32** [denmire/INF2001-TeamprojectP9Grp6#7]
Task title ID: #07
Draw a use case diagram for developers to understand what are the roles involved and how they interact with the system.
Goal is to make sure that every role's interaction with the system is understood.
Considered complete when the diagram is drawn and understood by the team.
Allocated time is 1 day.

**Comment by denmire** [comment]
Diagram has been drawn as clearly as possible. No complaints from team so far.
Diagram is in the repo.
Considered complete.
Completed on 18th Sep.
